const color = {
  primary: '#C03839',
  white: '#FFFFFF',
  mainGradian: '#F66667',
  main: '#C03839',
  border: '#F5F5F5',
  textColor: '#A3A3A3',
  textColor2: '#434343',
  textColor5: '#A0A0A0',
  labelColor: '#888888',
  currentStepColor: '#CDEAFF',
};
export const Colors = {
  primary: color.primary,
  main: color.main,
  mainGradian: color.mainGradian,
  splash_bg: [color.primary],
  tab_inactive_color: color.labelColor,
  tab_active_color: color.primary,
  tabbar_background: color.white,
  inputBorderActiveColor: color.main,
  inputBorderInactiveColor: color.border,
  textColor: color.textColor,
  textColor2: color.textColor2,
  textColor3: '#313131',
  textColor4: '#383B46',
  textColor5: color.textColor5,
  labelColor: color.labelColor,
  socialBorderColor: '#F9F9F9',
  activityBackgroundColor: color.border,
  enterOTPBorder: color.textColor5,
  currentStepColor: color.currentStepColor,
  popoverBackground: 'rgb(45, 45, 45)',
  blue: '#00A3FF',
  white: '#FFF',
  green: '#38C43B',
  orange: '#FC7C00',
  red: '#EC1D25',
  black: '#000000',
  black70: '#00000070',
  grey: '#86899B',
  border: color.border,
  text: '#2F3035',
  backgroundAvatar: '#CEF6FE',
  notificationUnreadBackground: '#F0F9FF',
  notificationBadge: '#FF5B05',
  backgroundScreen: '#F9F9F9',
  bannerHeaderHome: ['#C03839', '#FF7A7B'],
  homeCrmBackground: 'rgba(255, 198, 0, 0.1)',
};
export const shadow = (x, y, radius, color, shadowOpacity) => ({
  shadowColor: color,
  shadowOffset: {
    width: x,
    height: y,
  },
  shadowRadius: radius,
  shadowOpacity,
  elevation: 10,
});
